desugaring is mandatory for old android version to avoid
avoids NoClassDefFoundError: Failed resolution of: Ljava/time/Duration missing in android java classes

avoids $ExternalSyntheticLambda1

See https://github.com/nova-video-player/aos-AVP/issues/829
See https://github.com/hierynomus/smbj/issues/807
See https://github.com/jupnp/jupnp/issues/236