Revert "jsch 0.2.11 upstep"
This reverts commit cd784e0f05c1facb2d57f5b6a9aa6e615814ec41.

Fixes CI

```
> Task :mergeNoamazonReleaseGeneratedProguardFiles
> Task :minifyNoamazonReleaseWithR8
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/runner/work/aos-FileCoreLibrary/aos-FileCoreLibrary/nova/Video/build/outputs/mapping/noamazonRelease/missing_rules.txt.
ERROR: R8: Missing class org.bouncycastle.crypto.DefaultBufferedBlockCipher (referenced from: void com.jcraft.jsch.bc.CAST128CBC.init(int, byte[], byte[]) and 2 other contexts)
Missing class org.bouncycastle.crypto.modes.CBCModeCipher (referenced from: void com.jcraft.jsch.bc.CAST128CBC.init(int, byte[], byte[]) and 2 other contexts)
Missing class org.bouncycastle.crypto.modes.CTRModeCipher (referenced from: org.bouncycastle.crypto.modes.CTRModeCipher com.jcraft.jsch.bc.CAST128CTR.cipher and 5 other contexts)

> Task :minifyNoamazonReleaseWithR8 FAILED
```